image: python:latest  # Imagem Docker com Python

stages:
  - test

test:
  stage: test
  script:
    - pip install pytest
    - pip install pddl
    - pytest --cov=my_project --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml # Execute os testes no diretório "tests"

