image: python:latest  # Imagem Docker com Python

stages:
  - test

test:
  stage: test
  script:
    - pip install pytest pytest-cov pddl
    - pytest --cov --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
