image: python:latest  # Imagem Docker com Python

stages:
  - test

test:
  stage: test
  script:
    - pip install pytest
    - pip install pddl
    - pytest  # Execute os testes no diretório "tests"

