image: python:latest 

stages:
  - test

test:
  stage: test
  script:
    - pip install pytest pytest-cov pddl
    - pytest --cov --cov-report=xml
  coverage: '/TOTAL\s+\d+\.\d+%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
