image: python:latest 

stages:
  - test

test:
  stage: test
  script:
    - pip install pytest pytest-cov pddl
    - pytest --cov=src --cov-report=xml
  coverage: /TOTAL.*\s+(\d+%)$/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml 
    expire_in: never
